services:
  front:
    build:
      context: ./front
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - api-gateway

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "4000:80"
    depends_on:
      - iam
      - users
      - posts
      - notifications

  iam:
    build:
      context: ./microservices/iam
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
      - NODE_ENV=production

  users:
    build:
      context: ./microservices/users
    ports:
      - "4002:4002"
    environment:
      - PORT=4002
      - NODE_ENV=production

  posts:
    build:
      context: ./microservices/posts
    ports:
      - "4003:4003"
    environment:
      - PORT=4003
      - NODE_ENV=production

  notifications:
    build:
      context: ./microservices/notifications
    ports:
      - "4004:4004"
    environment:
      - PORT=4004
      - NODE_ENV=production
